// <auto-generated />
namespace ToDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inclusao_Campo_UserName_Model_Tarefas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusao_Campo_UserName_Model_Tarefas));
        
        string IMigrationMetadata.Id
        {
            get { return "201610161316192_Inclusao_Campo_UserName_Model_Tarefas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
